# Generated by Django 4.1.7 on 2023-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_shop_street_street_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='street',
        ),
        migrations.AddField(
            model_name='shop',
            name='street',
            field=models.ManyToManyField(related_name='street_shop', to='backend.street'),
        ),
    ]
